spring.datasource.url=jdbc:postgresql://ep-purple-grass-aqtkgrny-pooler.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_AjxztoV6PfQ8&sslmode=require&channelBinding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_AjxztoV6PfQ8

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
